### PR TITLE
Large Part Splits

### PR DESCRIPTION
**Pull request by timmit99**
Split the largest components (Receiver and Barrel) into seperate parts with indexing lugs for printing on non 500+mm Axis printers. The rear section of the receiver is 199.9mm so it would be best on a 250mm printer but can work if you have a bit over 200mm on your machine.

### CODE REVIEW

**Review by Ansuzalgiz — CHANGES_REQUESTED** [review]
Can you orient parts for printing?

**Comment by timmit99** [comment]
Sure thing. I'll rotate them in meshmixer and resubmit

**Comment by timmit99** [comment]
Changes have been made.

**Review by Ansuzalgiz — APPROVED** [review]

**Comment by Ansuzalgiz** [comment]
Thanks! I know this is something people want, but I haven't been very motivated to do.

**Pull request merged**
